### ISSUE TITLE
Phidget throws error when to set phidget output second time

### ISSUE THREAD

**Issue by rajivsavroop** [RIAEvangelist/node-phidget-API#32]
Started
in phi test
I am connected
yeah im attached { type: 'board',
  key: 'Status',
  value: 'Attached',
  Status: 'Attached' }
Phidget is ready to be tested
.ending before
.starting after
changed value 1
{ serial: '263991',
  board: 
   { InitKeys: '17',
     ID: '129',
     NumberOfOutputs: '8',
     NumberOfInputs: '0',
     NumberOfSensors: '0',
     Status: 'Attached',
     Name: 'Phidget InterfaceKit 0/0/8',
     Version: '100',
     Label: '' },
  Output: 
   { '0': '1',
     '1': '0',
     '2': '0',
     '3': '0',
     '4': '0',
     '5': '0',
     '6': '0',
     '7': '0' } }
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at EventEmitter.emit (events.js:87:13)
    at EventEmitter.set (/home/rkumar/Git/node-phidget-API/lib/Phidget.js:318:26)
    at EventEmitter.testCase (/home/rkumar/Git/node-phidget-API/spec/support/phidgetTest/tests/phidgets.spec.js:177:33)
    at EventEmitter.emit (events.js:107:17)
    at EventEmitter.update (/home/rkumar/Git/node-phidget-API/lib/Phidget.js:173:26)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by RIAEvangelist** [comment]
@rajivsavroop this seems related to the test running the set command from what you showed me today.

**Comment by RIAEvangelist** [comment]
fixed in PR #35 from @rajivsavroop

**Comment by RIAEvangelist** [comment]
fixed as of npm v2.2.8
